@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.github.elenterius.bakingbread.datagen.recipes;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;